language: node_js
node_js:
  - "stable"
script:
  - cd frontend
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
